[project]
name = "dtach-utils"
version = "0.1.0"
description = "Dtach support scripts (find first free socket, get socket from window)"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[build-system]
requires = ["setuptools"]

[project.optional-dependencies]
x11 = [
    "xlib>=0.21",
]
i3 = [
    "i3ipc>=2.2.1",
]

[project.scripts]
new = "new:main"
x11-winid-to-sock = "x11_win_id_to_sock:main"

[tool.black]
line-length = 120
