export alias g = git
export alias gpf = git push --force-with-lease
export alias grp = git reset -p
export alias gprev = git reset HEAD^
export alias gpprev = git reset -p HEAD^
export alias nixrepl = nix repl --expr 'builtins.getFlake "nixos-config"';
export alias ll = ls -l
export alias la = ls -la
export alias n = ^nix
export alias nf = ^nix flake
export alias nb = ^nom build
export alias der = direnv reload
export alias ded = direnv edit
export alias termbin = nc termbin.com 9999
