#!/usr/bin/env python3
from pye_menu import TopMenu, SubMenu, MenuItem, SubMenuItem, ExecMenuItem
import subprocess

if __name__ == '__main__':
    subprocess.run(["@i3msg@", "--", "mark", "--add", "previous"],
            stdout=subprocess.DEVNULL)
    try:
        TopMenu(
          ExecMenuItem("Close", ["@i3msg@", "[con_mark=previous]", "kill"]),
          ExecMenuItem("Fullscreen", ["@i3msg@", "[con_mark=previous]",
              "fullscreen", "toggle"]),
          ExecMenuItem("Float", ["@i3msg@", "[con_mark=previous]",
              "floating", "toggle"]),
          SubMenuItem("Music",
              ExecMenuItem("⏯️", ["@mpc@", "toggle"]),
              ExecMenuItem("1", ["@mpc@", "single"]),
              ExecMenuItem("⏭", ["@mpc@", "next"]),
              ExecMenuItem("⏹", ["@mpc@", "stop"]),
              ExecMenuItem("⏮", ["@mpc@", "prev"]),
              ExecMenuItem("🔁️", ["@mpc@", "loop"])),
          SubMenuItem("Actions",
              ExecMenuItem("Screenshot", ["scrot"]),
              SubMenuItem("Rotate",
                  ExecMenuItem("Normal", ["/home/rmk35/bin/rotate", "normal"]),
                  ExecMenuItem("Right", ["/home/rmk35/bin/rotate", "right"]),
                  ExecMenuItem("Inverted", ["/home/rmk35/bin/rotate", "inverted"]),
                  ExecMenuItem("Left", ["/home/rmk35/bin/rotate", "left"]),
                  radius=300),
              ExecMenuItem("Lock", ["@loginctl@", "lock-session"]),
              ExecMenuItem("Quit", ["@i3msg@", "quit"]),
              radius=300),
          radius=400).main()
    finally:
        subprocess.run(["@i3msg@", "unmark", "previous"],
                stdout=subprocess.DEVNULL)
