#!/bin/sh

#   post-checkout
#     This hook is invoked when a git-checkout(1) or git-switch(1) is
#     run after having updated the worktree. The  hook is  given  three
#     parameters:  the  ref of the previous HEAD, the ref of the new HEAD
#     (which may or may not have changed), and a flag indicating whether
#     the checkout was a branch checkout (changing branches, flag=1) or
#     a file checkout (retrieving a file from the index, flag=0). This
#     hook cannot affect the outcome of git  switch  or  git checkout,
#     other than that the hook’s exit status becomes the exit status
#     of these two commands.
#
#     It  is  also  run after git-clone(1), unless the --no-checkout
#     (-n) option is used. The first parameter given to the hook is the
#     null-ref, the second the ref of the new HEAD and the flag is always
#     1. Likewise for git worktree add unless --no-checkout is used.
#
#     This hook can be used to perform repository validity checks,
#     auto-display differences from the previous HEAD  if different,
#     or set working dir metadata properties.

if [ "$(git config --bool --get lfs.disable)" != true ]; then
    command -v git-lfs >/dev/null 2>&1 || { printf >&2 "\n%s\n\n" "This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'post-checkout' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks')."; exit 2; }
    git lfs post-checkout "$@"
fi
