#!/bin/sh


#   post-merge
#     This  hook  is  invoked  by  git-merge(1), which happens when a
#     git pull is done on a local repository. The hook takes a single
#     parameter, a status flag specifying whether or not the merge being
#     done was a squash merge.  This hook cannot affect the outcome of
#     git merge and is not executed, if the merge failed due to conflicts.
#
#     This  hook can be used in conjunction with a corresponding pre-commit
#     hook to save and restore any form of meta‐ data associated with
#     the working  tree  (e.g.:  permissions/ownership,  ACLS,  etc).
#     See  contrib/hooks/setgit‐ perms.perl for an example of how to
#     do this.

if [ "$(git config --bool --get lfs.disable)" != true ]; then
    command -v git-lfs >/dev/null 2>&1 || { printf >&2 "\n%s\n\n" "This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'post-merge' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks')."; exit 2; }
    git lfs post-merge "$@"
fi
