#!/bin/sh

set -eu

if [ $# != 1 ]; then
  echo "Usage: $0 <file>"
  echo "  Edits <file> in the git index in \$EDITOR"
  exit 1
fi
FILE="$(basename "$1")"
REPO="$(git rev-parse --show-toplevel)"
REPOFILE="$(realpath --relative-to="$REPO" "$1")"
GITDIR="$(git rev-parse --git-dir)"
TMPDIR="$GITDIR/edit-index"
mkdir -p "$TMPDIR"
TEMPFILE="$(mktemp --tmpdir="$TMPDIR" --suffix ".$FILE")"
MODE=$(git ls-files --stage "$REPOFILE" | cut -d' ' -f1)
if [ -t 0 ]; then
  if [ -n "$MODE" ]; then
    # Read existing staged file contents
    git cat-file blob ":0:$REPOFILE" >"$TEMPFILE" 2>/dev/null
  fi
  if ! $EDITOR "$TEMPFILE"; then
    echo "Keeping temporary file $TEMPFILE"
    exit 1
  fi
else
  cat >"$TEMPFILE"
fi
# Sensible default for files, git doesn't track directories
MODE=${MODE:-100644}
HASH="$(git hash-object -w "$TEMPFILE")"
rm "$TEMPFILE"
git update-index --add --cacheinfo "$MODE,$HASH,$REPOFILE"
