#!/bin/sh

set -eu

if [ $# != 1 ]; then
  echo "Usage: $0 <file>"
  echo "  Edits <file> in the git index in \$EDITOR"
  exit 1
fi
FILE="$(basename "$1")"
GITDIR="$(git rev-parse --git-dir)"
TMPDIR="$GITDIR/edit-index"
mkdir -p "$TMPDIR"
TEMPFILE="$(mktemp --tmpdir="$TMPDIR" --suffix ".$FILE")"
MODE=$(git ls-files --stage "$1" | cut -d' ' -f1)
if [ -n "$MODE" ]; then
  # Read existing staged file contents
  git cat-file blob ":0:$1" >"$TEMPFILE" 2>/dev/null
else
  # Sensible default for files, git doesn't track directories
  MODE=100644
fi
if $EDITOR "$TEMPFILE"; then
  HASH="$(git hash-object -w "$TEMPFILE")"
  rm "$TEMPFILE"
  git update-index --add --cacheinfo "$MODE,$HASH,$1"
else
  echo "Keeping temporary file $TEMPFILE"
fi
