# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.loader.grub.enable = true;
  boot.loader.grub.version = 2;
  boot.loader.grub.device = "/dev/sda"; # or "nodev" for efi only

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/11f46fea-7151-49cd-947f-16693f52e094";
      fsType = "xfs";
    };

  boot.initrd.luks.devices."cc-nixos-a".device = "/dev/disk/by-uuid/98512b43-21cc-4167-b117-7ca792debb2a";

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/3B18-E9E9";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "20.09"; # Did you read the comment?

}
