# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" "sr_mod" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  boot.initrd.luks.devices."rmk-cc-b" =
    {
      device = "/dev/disk/by-uuid/d9e7347c-5ced-4cd7-8e16-31d6f9d209be";
      allowDiscards = true;
    };

  fileSystems = {
    "/" =
      {
        device = "/dev/disk/by-uuid/cb457367-01c5-4a32-a377-64bd672a69ae";
        fsType = "xfs";
      };

    "/boot" =
      {
        device = "/dev/disk/by-uuid/FF3D-5AFB";
        fsType = "vfat";
      };
  };

  swapDevices =
    [{
      device = "/dev/disk/by-uuid/0bb302f3-d334-4159-82cb-88daa5e07486";
    }];

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "23.05"; # Did you read the comment?
  home-manager.users.default-user.home.stateVersion = "23.05";

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
